name: test

on:
  push:
  pull_request:

jobs:


  lin:
    strategy:
      fail-fast: false
      matrix:
        os: [
          '18.04',
          '20.04'
        ]
    runs-on: ubuntu-${{ matrix.os }}
    name: '🐧 Ubuntu ${{ matrix.os }}'
    steps:

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update -qq
        sudo apt install -y make g++ git bison flex gperf libreadline-dev autoconf

    - name: Build
      run: |
        autoconf
        ./configure
        sudo make install
        make check

    - name: Test
      run: ./.github/test.sh


  win:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          {
            label: '🧊 Windows',
            msystem: MINGW64,
            arch: x86_64,
            release: false,
            shell: mingw64,
          },
          {
            label: '🟪 MSYS2',
            msystem: MINGW64,
            arch: x86_64,
            release: true,
            shell: msys2,
          },
          {
            label: '🟪 MSYS2',
            msystem: MINGW32,
            arch: i686,
            release: true,
            shell: msys2,
          }
        ]
    name: ${{ matrix.label }} · ${{ matrix.msystem}}
    defaults:
      run:
        shell: ${{ matrix.shell }} {0}
    env:
      MINGW_INSTALLS: ${{ matrix.msystem }}
    steps:

    - name: Setup
      shell: bash
      run: |
        git config --global core.autocrlf input
        echo "$(cygpath -w $(pwd)/.github/bin)" >> $GITHUB_PATH

    - uses: actions/checkout@v2

    - uses: msys2/setup-msys2@v2
      with:
        release: ${{ matrix.release }}
        msystem: ${{ matrix.msystem }}
        install: >
          git
          base-devel
          mingw-w64-${{ matrix.arch }}-toolchain
        update: true

    - name: 🧊 Build, install and check
      if: matrix.shell == 'mingw64'
      run: |
        wrap() { echo "::group::$@"; "$@"; echo '::endgroup::'; }
        wrap ./autoconf.sh
        wrap ./configure
        wrap make install
        which iverilog
        wrap make check

    - name: 🟪 Build and check
      if: matrix.shell == 'msys2'
      run: |
        cd msys2
        makepkg-mingw --noconfirm --noprogressbar -sCLf

    - name: 🟪 Install
      if: matrix.shell == 'msys2'
      run: pacman -U --noconfirm msys2/*.zst

    - name: Test
      run: ./.github/test.sh
